### ISSUE TITLE
Optimise database interface

### ISSUE THREAD

**Issue by mitchts** [Group4-3/ESSW#17]

**Comment by techno156** [comment]
Rewrite/modifications needed to add in functions that deal with implemented optional features brought up at 2022-08-16 client meeting, such as syntax highlighting, and allowing the insertion of binary blob files into the database, or alternate storage methods for such files.

----

Storage can occur either through the database, or in the local file system, using a hash of the name and checksum of the contents, which is then mapped to the original filename via a second database table.

**Comment by techno156** [comment]
[Discussion needed to determine implementation of above]

**Comment by techno156** [comment]
Above implementation related to #38
