### ISSUE TITLE
Docker image fails to load: Cannot find module '/home/node/app/node_modules/sqlite3/lib/binding/napi-v6-linux-glibcx64/node_sqlite3.node' on Windows systems

### ISSUE THREAD

**Issue by techno156** [Group4-3/ESSW#48]
Cannot find module '/home/node/app/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node' on Windows systems.

This likely occurs as a result of node loading windows versions of the packages.

The appropriate path contains 'napi-v6-win32-unknown-x64' instead of of '*-linux/glibc-x64' on Windows systems.

Found by @alejarsz.

**Comment by petribayley** [comment]
I'm unable to replicate, is problem still occurring with latest build?
